baseURL = "https://zira.my.id"
defaultContentLanguage = "id"

paginate = 10
enableEmoji = true

[imaging]
  anchor = 'Center'

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[related]
 threshold = 0
 toLower = false

[[related.indices]]
  name = "date"
  weight = 10

[[related.indices]]
  applyFilter = false
  name = 'fragmentrefs'
  type = 'fragments'
  weight = 10
